[package]
name = "srth/doopley"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Shake = "sleitnick/shake@1.1.0"
Timer = "sleitnick/timer@1.1.2"
Component = "sleitnick/component@2.4.8"
Net = "sleitnick/net@0.2.0"
