return{
    "Heler",
    "Can you Send me",
    "ab, windows",
    "cup is schizo",
    "aaaaaaaaaaahahahaa",
	"高端的食材往往只需要采用最朴素的烹饪方式",
    "thumbs up game pleas",
    "喂，你好吗",
    "厕所",
    "四吨",
    "ألفي بيضة مع الأرز",
    "15689943423",
    "Humanoid",
    "ADOMI55 CHICEN",
    "Im soooooooooooooooooooooooooooooooooooooooo H",
    "?q/??????",
    "请十四扇门",
    "计算机正在进入",
    "蛋卷?????🌮",
    "我的手机是冷的",
    "请将 USB 设备连接到",
    "这太有趣了🤣🤣🤣🤣🤣🤣🤣",
    "Roblox 已关闭",
    "蓝牙设备已连接",
    "感谢您选择梨",
    "将偏移量应用于关联的模型",
    "Clouds 对象渲染在天空中缓慢漂移的逼真云。",
    "颜色 颜色3 并行读取",
    "因此，始终建议调用 Instance：Destroy（）",
    "碎片：AddItem（brick， 3）",
    "荒废的 Flag 和 FlagStand 对象是",
    "团队颜色：BrickColor 并行读取 荒废的 这面旗帜是针对的团队。科雷斯",
    "UI 层次结构中的每个文件夹都可以定义自己的 UILayout（UIListLayout、UIGridLayout、UIPageLayout、UITableLayout）",
    "клиент. Используется",
    "Это забавная машина",
    "Девятнадцать🤣🤣",
    "Асарагус",
    "Двенадцать апельсинов",
    "Дупли",
    "GuiBase - это абстрактный класс, от которого наследуется большинство объектов графического пользовательского интерфейса.",
    "Свойства Просмотреть все, унаследованное от Instance",
    "Вас выгнали",
    "You Have Been Kicked",
    "I Dont have A Brother",
    "хджахахаха",
    "im Gon",
    "Ice Cream......",
    "Domi e e fifty five",
	"ywywiq nwmqgh wujrfo",
    "@@@@@!!!!!!!!!!!f!!!!!",
    "Sausage on a Stick",
    "Do you like Orange Cars?",
    "2",
    "1",
    "3",
    "4",
	"5",
	"This item is not currently for sale.",
    "im laffing🤣🤣🤣🤣🤣🤣",
    "🐫",
    "Pineapple Trees",
    "cooking the slipper",
    "+)!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "p",
	"Making Creation and Expression Easier for Anyone In Marketplace (",
	"𝓷",
	"🍪  🎀  𝓈𝓉𝑒𝓅𝓅𝒾𝓃𝑔 ♡𝓃 𝒶 𝓈🌺𝒶𝓅 𝓌𝒾𝓁𝓁 𝓂𝒶𝓀𝑒 𝓎❁𝓊 𝒻𝒶𝓁𝓁  🎀  🍪",
	"Bine ați venit la Baldis Basics, educațional și învățare, asta sunt eu",
	"ｂｌｏｗ ｔｈｅ ｇｒａｓｓ",
	"♐︎●︎⍓︎♓︎■︎♑︎ □︎■︎ ♋︎ ♍︎♒︎♏︎❒︎❒︎⍓︎ ◻︎♓︎♏︎",
	"☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺☺",
	"☺",
	"ဩdا صصصص ي 3",
    "y",
	"ᚙᚙᚙᚙᚙᚙ✔ᚙᚙ✔✔ᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙ✔✔ᚙᚙᚙᚙᚙᚙ𒁎 ꧅𒀱꧅𒌧𒅃꧅꧅꧅ᚙᚙᚙᚙᚙᚙᚙ✔ᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙᚙ",
	"𒁎 ꧅𒀱꧅𒌧𒁎 ꧅𒀱꧅𒌧𒅃꧅꧅꧅꧅꧅",
    "♋︎ ♍︎♒︎♏︎❒︎❒︎⍓︎",
    "LOL!",
    "Deniz hiding his Lolipops",
    "ه مخرث ثشفهىل لاشىشىشس!"    
}